/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-287a6e5c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-287a6e5c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-b3d972fa",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b3d972fa").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-9dc031c8",
    path: "/bar/a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9dc031c8").then(next)
    },
  },
  {
    name: "v-f407a51c",
    path: "/accumulate/accumulate/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f407a51c").then(next)
    },
  },
  {
    path: "/accumulate/accumulate/index.html",
    redirect: "/accumulate/accumulate/"
  },
  {
    name: "v-854e8066",
    path: "/es6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-854e8066").then(next)
    },
  },
  {
    path: "/es6/index.html",
    redirect: "/es6/"
  },
  {
    name: "v-3c391842",
    path: "/es6/commonly/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c391842").then(next)
    },
  },
  {
    path: "/es6/commonly/index.html",
    redirect: "/es6/commonly/"
  },
  {
    name: "v-dda5f9fc",
    path: "/es6/note/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dda5f9fc").then(next)
    },
  },
  {
    path: "/es6/note/index.html",
    redirect: "/es6/note/"
  },
  {
    name: "v-68da2ad5",
    path: "/fe/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68da2ad5").then(next)
    },
  },
  {
    path: "/fe/index.html",
    redirect: "/fe/"
  },
  {
    name: "v-025cf075",
    path: "/link/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-025cf075").then(next)
    },
  },
  {
    path: "/link/index.html",
    redirect: "/link/"
  },
  {
    name: "v-53a7f95e",
    path: "/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53a7f95e").then(next)
    },
  },
  {
    path: "/vue/index.html",
    redirect: "/vue/"
  },
  {
    name: "v-4073a1d5",
    path: "/webframe/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4073a1d5").then(next)
    },
  },
  {
    path: "/webframe/index.html",
    redirect: "/webframe/"
  },
  {
    name: "v-a357d5b0",
    path: "/webframe/es6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a357d5b0").then(next)
    },
  },
  {
    path: "/webframe/es6/index.html",
    redirect: "/webframe/es6/"
  },
  {
    name: "v-143969c2",
    path: "/webframe/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-143969c2").then(next)
    },
  },
  {
    name: "v-797ac6c1",
    path: "/webframe/vue/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-797ac6c1").then(next)
    },
  },
  {
    name: "v-2d76c44e",
    path: "/works/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d76c44e").then(next)
    },
  },
  {
    path: "/works/index.html",
    redirect: "/works/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]