/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/usr/local/lib/node_modules/vuepress/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-665ef4b2",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-665ef4b2").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-c4dec794",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c4dec794").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-9e301400",
    path: "/entertainment/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9e301400").then(next)
    },
  },
  {
    path: "/entertainment/index.html",
    redirect: "/entertainment/"
  },
  {
    name: "v-71737772",
    path: "/accumulate/accumulate/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71737772").then(next)
    },
  },
  {
    path: "/accumulate/accumulate/index.html",
    redirect: "/accumulate/accumulate/"
  },
  {
    name: "v-81600978",
    path: "/codes/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-81600978").then(next)
    },
  },
  {
    path: "/codes/index.html",
    redirect: "/codes/"
  },
  {
    name: "v-54b9d1ee",
    path: "/bar/a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54b9d1ee").then(next)
    },
  },
  {
    name: "v-4ae95e40",
    path: "/es6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ae95e40").then(next)
    },
  },
  {
    path: "/es6/index.html",
    redirect: "/es6/"
  },
  {
    name: "v-753bfa7c",
    path: "/es6/commonly/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-753bfa7c").then(next)
    },
  },
  {
    path: "/es6/commonly/index.html",
    redirect: "/es6/commonly/"
  },
  {
    name: "v-874c81fc",
    path: "/es6/note/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-874c81fc").then(next)
    },
  },
  {
    path: "/es6/note/index.html",
    redirect: "/es6/note/"
  },
  {
    name: "v-803d047c",
    path: "/fe/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-803d047c").then(next)
    },
  },
  {
    path: "/fe/index.html",
    redirect: "/fe/"
  },
  {
    name: "v-7ab15142",
    path: "/fe/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ab15142").then(next)
    },
  },
  {
    path: "/fe/css/index.html",
    redirect: "/fe/css/"
  },
  {
    name: "v-098ea0a2",
    path: "/fe/css/world/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-098ea0a2").then(next)
    },
  },
  {
    path: "/fe/css/world/index.html",
    redirect: "/fe/css/world/"
  },
  {
    name: "v-c79d167c",
    path: "/fe/js/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c79d167c").then(next)
    },
  },
  {
    path: "/fe/js/js/index.html",
    redirect: "/fe/js/js/"
  },
  {
    name: "v-2d9895c4",
    path: "/fe/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d9895c4").then(next)
    },
  },
  {
    path: "/fe/js/index.html",
    redirect: "/fe/js/"
  },
  {
    name: "v-edd5164c",
    path: "/fe/html/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-edd5164c").then(next)
    },
  },
  {
    path: "/fe/html/index.html",
    redirect: "/fe/html/"
  },
  {
    name: "v-7a9f2fd0",
    path: "/fe/js/design-patterns-and-data-structures/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a9f2fd0").then(next)
    },
  },
  {
    path: "/fe/js/design-patterns-and-data-structures/index.html",
    redirect: "/fe/js/design-patterns-and-data-structures/"
  },
  {
    name: "v-70583ffa",
    path: "/fe/source/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70583ffa").then(next)
    },
  },
  {
    path: "/fe/source/index.html",
    redirect: "/fe/source/"
  },
  {
    name: "v-4d6e5dea",
    path: "/fe/qt/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d6e5dea").then(next)
    },
  },
  {
    path: "/fe/qt/index.html",
    redirect: "/fe/qt/"
  },
  {
    name: "v-6321ce30",
    path: "/link/source/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6321ce30").then(next)
    },
  },
  {
    path: "/link/source/index.html",
    redirect: "/link/source/"
  },
  {
    name: "v-63bca1c4",
    path: "/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63bca1c4").then(next)
    },
  },
  {
    path: "/vue/index.html",
    redirect: "/vue/"
  },
  {
    name: "v-3ac64f42",
    path: "/future/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ac64f42").then(next)
    },
  },
  {
    path: "/future/index.html",
    redirect: "/future/"
  },
  {
    name: "v-429515e2",
    path: "/fe/js/webpack/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-429515e2").then(next)
    },
  },
  {
    path: "/fe/js/webpack/index.html",
    redirect: "/fe/js/webpack/"
  },
  {
    name: "v-3b538b7c",
    path: "/vue/note/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b538b7c").then(next)
    },
  },
  {
    path: "/vue/note/index.html",
    redirect: "/vue/note/"
  },
  {
    name: "v-2a164f76",
    path: "/vue/excellent/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a164f76").then(next)
    },
  },
  {
    path: "/vue/excellent/index.html",
    redirect: "/vue/excellent/"
  },
  {
    name: "v-b2bb5ebc",
    path: "/vue/source/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b2bb5ebc").then(next)
    },
  },
  {
    path: "/vue/source/index.html",
    redirect: "/vue/source/"
  },
  {
    name: "v-151077bc",
    path: "/link/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-151077bc").then(next)
    },
  },
  {
    path: "/link/index.html",
    redirect: "/link/"
  },
  {
    name: "v-1c074e96",
    path: "/webframe/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c074e96").then(next)
    },
  },
  {
    name: "v-afc431fc",
    path: "/webframe/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-afc431fc").then(next)
    },
  },
  {
    path: "/webframe/index.html",
    redirect: "/webframe/"
  },
  {
    name: "v-01aac022",
    path: "/webframe/es6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01aac022").then(next)
    },
  },
  {
    path: "/webframe/es6/index.html",
    redirect: "/webframe/es6/"
  },
  {
    name: "v-e34c2ff2",
    path: "/webframe/vue/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e34c2ff2").then(next)
    },
  },
  {
    name: "v-3e7c18e8",
    path: "/works/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e7c18e8").then(next)
    },
  },
  {
    path: "/works/index.html",
    redirect: "/works/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]