/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-1c16ff70",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c16ff70").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-5eb6ffbe",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5eb6ffbe").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-3ee121e0",
    path: "/accumulate/accumulate/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ee121e0").then(next)
    },
  },
  {
    path: "/accumulate/accumulate/index.html",
    redirect: "/accumulate/accumulate/"
  },
  {
    name: "v-3b077b84",
    path: "/bar/a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b077b84").then(next)
    },
  },
  {
    name: "v-4b53786b",
    path: "/es6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b53786b").then(next)
    },
  },
  {
    path: "/es6/index.html",
    redirect: "/es6/"
  },
  {
    name: "v-976fe3c0",
    path: "/es6/note/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-976fe3c0").then(next)
    },
  },
  {
    path: "/es6/note/index.html",
    redirect: "/es6/note/"
  },
  {
    name: "v-40c672f3",
    path: "/fe/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40c672f3").then(next)
    },
  },
  {
    path: "/fe/index.html",
    redirect: "/fe/"
  },
  {
    name: "v-06e80cda",
    path: "/link/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06e80cda").then(next)
    },
  },
  {
    path: "/link/index.html",
    redirect: "/link/"
  },
  {
    name: "v-6426bbef",
    path: "/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6426bbef").then(next)
    },
  },
  {
    path: "/vue/index.html",
    redirect: "/vue/"
  },
  {
    name: "v-638eacf3",
    path: "/webframe/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-638eacf3").then(next)
    },
  },
  {
    path: "/webframe/index.html",
    redirect: "/webframe/"
  },
  {
    name: "v-bb02bd38",
    path: "/webframe/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bb02bd38").then(next)
    },
  },
  {
    name: "v-518dbb74",
    path: "/webframe/es6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-518dbb74").then(next)
    },
  },
  {
    path: "/webframe/es6/index.html",
    redirect: "/webframe/es6/"
  },
  {
    name: "v-79e73c63",
    path: "/webframe/vue/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79e73c63").then(next)
    },
  },
  {
    name: "v-13d5d777",
    path: "/works/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13d5d777").then(next)
    },
  },
  {
    path: "/works/index.html",
    redirect: "/works/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]