/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "200s's 的个人博客区",
  "description": "我的个人网站",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/logo.jpg"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "欢迎访问",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-200s"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-287a6e5c",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-b3d972fa",
      "path": "/about/"
    },
    {
      "frontmatter": {},
      "regularPath": "/accumulate/accumulate/",
      "relativePath": "accumulate/accumulate/README.md",
      "key": "v-f407a51c",
      "path": "/accumulate/accumulate/"
    },
    {
      "frontmatter": {},
      "regularPath": "/bar/a.html",
      "relativePath": "bar/a.md",
      "key": "v-9dc031c8",
      "path": "/bar/a.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/es6/",
      "relativePath": "es6/README.md",
      "key": "v-854e8066",
      "path": "/es6/"
    },
    {
      "frontmatter": {},
      "regularPath": "/fe/",
      "relativePath": "fe/README.md",
      "key": "v-68da2ad5",
      "path": "/fe/"
    },
    {
      "frontmatter": {},
      "regularPath": "/link/",
      "relativePath": "link/README.md",
      "key": "v-025cf075",
      "path": "/link/"
    },
    {
      "frontmatter": {},
      "regularPath": "/es6/note/",
      "relativePath": "es6/note/README.md",
      "key": "v-dda5f9fc",
      "path": "/es6/note/"
    },
    {
      "frontmatter": {},
      "regularPath": "/vue/",
      "relativePath": "vue/README.md",
      "key": "v-53a7f95e",
      "path": "/vue/"
    },
    {
      "frontmatter": {},
      "regularPath": "/webframe/",
      "relativePath": "webframe/README.md",
      "key": "v-4073a1d5",
      "path": "/webframe/"
    },
    {
      "title": "es6 目录",
      "frontmatter": {},
      "regularPath": "/webframe/es6/",
      "relativePath": "webframe/es6/README.md",
      "key": "v-a357d5b0",
      "path": "/webframe/es6/",
      "headers": [
        {
          "level": 2,
          "title": "es6 目录",
          "slug": "es6-目录"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/webframe/vue.html",
      "relativePath": "webframe/vue.md",
      "key": "v-143969c2",
      "path": "/webframe/vue.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/webframe/vue/vue.html",
      "relativePath": "webframe/vue/vue.md",
      "key": "v-797ac6c1",
      "path": "/webframe/vue/vue.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/works/",
      "relativePath": "works/README.md",
      "key": "v-2d76c44e",
      "path": "/works/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "前端",
        "link": "/fe/"
      },
      {
        "text": "es6",
        "link": "/es6/"
      },
      {
        "text": "前端框架",
        "items": [
          {
            "text": "vue",
            "link": "/vue/"
          }
        ]
      },
      {
        "text": "社区",
        "items": [
          {
            "text": "掘金",
            "link": "https://juejin.im/user/1310273588955581"
          },
          {
            "text": "github",
            "link": "https://juejin.im/user/1310273588955581"
          },
          {
            "text": "微博",
            "link": "https://weibo.com/fangjiayu1107"
          }
        ]
      },
      {
        "text": "我的作品",
        "link": "/works/"
      },
      {
        "text": "友情链接",
        "link": "/link/"
      },
      {
        "text": "关于",
        "link": "/about/"
      }
    ],
    "sidebar": {
      "/es6/": [
        [
          "",
          "目录"
        ],
        {
          "title": "笔记",
          "path": "/es6/note/",
          "collapsable": false,
          "sidebarDepth": 1
        }
      ]
    }
  }
}