/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "200s's 的个人博客区",
  "description": "我的个人网站",
  "base": "/vuepressBlogDemo",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/vuepressBlogDemologo.jpg"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "欢迎访问",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-200s"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-665ef4b2",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-c4dec794",
      "path": "/about/"
    },
    {
      "frontmatter": {},
      "regularPath": "/entertainment/",
      "relativePath": "entertainment/README.md",
      "key": "v-9e301400",
      "path": "/entertainment/"
    },
    {
      "frontmatter": {},
      "regularPath": "/accumulate/accumulate/",
      "relativePath": "accumulate/accumulate/README.md",
      "key": "v-71737772",
      "path": "/accumulate/accumulate/"
    },
    {
      "title": "0.vue基础(基础中出现)先隐藏部分再显示全部",
      "frontmatter": {},
      "regularPath": "/codes/",
      "relativePath": "codes/README.md",
      "key": "v-81600978",
      "path": "/codes/"
    },
    {
      "frontmatter": {},
      "regularPath": "/bar/a.html",
      "relativePath": "bar/a.md",
      "key": "v-54b9d1ee",
      "path": "/bar/a.html"
    },
    {
      "title": "0.es6基础总结01之let,var,count的理解",
      "frontmatter": {},
      "regularPath": "/es6/",
      "relativePath": "es6/README.md",
      "key": "v-4ae95e40",
      "path": "/es6/"
    },
    {
      "frontmatter": {},
      "regularPath": "/es6/commonly/",
      "relativePath": "es6/commonly/README.md",
      "key": "v-753bfa7c",
      "path": "/es6/commonly/"
    },
    {
      "frontmatter": {},
      "regularPath": "/es6/note/",
      "relativePath": "es6/note/README.md",
      "key": "v-874c81fc",
      "path": "/es6/note/"
    },
    {
      "frontmatter": {},
      "regularPath": "/fe/",
      "relativePath": "fe/README.md",
      "key": "v-803d047c",
      "path": "/fe/"
    },
    {
      "frontmatter": {},
      "regularPath": "/fe/css/",
      "relativePath": "fe/css/README.md",
      "key": "v-7ab15142",
      "path": "/fe/css/"
    },
    {
      "frontmatter": {},
      "regularPath": "/fe/css/world/",
      "relativePath": "fe/css/world/README.md",
      "key": "v-098ea0a2",
      "path": "/fe/css/world/"
    },
    {
      "frontmatter": {},
      "regularPath": "/fe/js/js/",
      "relativePath": "fe/js/js/README.md",
      "key": "v-c79d167c",
      "path": "/fe/js/js/"
    },
    {
      "title": "vue之moment简单的时间处理",
      "frontmatter": {},
      "regularPath": "/fe/js/",
      "relativePath": "fe/js/README.md",
      "key": "v-2d9895c4",
      "path": "/fe/js/"
    },
    {
      "frontmatter": {},
      "regularPath": "/fe/html/",
      "relativePath": "fe/html/README.md",
      "key": "v-edd5164c",
      "path": "/fe/html/"
    },
    {
      "frontmatter": {},
      "regularPath": "/fe/js/design-patterns-and-data-structures/",
      "relativePath": "fe/js/design-patterns-and-data-structures/README.md",
      "key": "v-7a9f2fd0",
      "path": "/fe/js/design-patterns-and-data-structures/"
    },
    {
      "frontmatter": {},
      "regularPath": "/fe/source/",
      "relativePath": "fe/source/README.md",
      "key": "v-70583ffa",
      "path": "/fe/source/"
    },
    {
      "frontmatter": {},
      "regularPath": "/fe/qt/",
      "relativePath": "fe/qt/README.md",
      "key": "v-4d6e5dea",
      "path": "/fe/qt/"
    },
    {
      "title": "OSCHINA - 中文开源技术交流社区",
      "frontmatter": {},
      "regularPath": "/link/source/",
      "relativePath": "link/source/README.md",
      "key": "v-6321ce30",
      "path": "/link/source/"
    },
    {
      "frontmatter": {},
      "regularPath": "/vue/",
      "relativePath": "vue/README.md",
      "key": "v-63bca1c4",
      "path": "/vue/"
    },
    {
      "frontmatter": {},
      "regularPath": "/future/",
      "relativePath": "future/README.md",
      "key": "v-3ac64f42",
      "path": "/future/"
    },
    {
      "frontmatter": {},
      "regularPath": "/fe/js/webpack/",
      "relativePath": "fe/js/webpack/README.md",
      "key": "v-429515e2",
      "path": "/fe/js/webpack/"
    },
    {
      "frontmatter": {},
      "regularPath": "/vue/note/",
      "relativePath": "vue/note/README.md",
      "key": "v-3b538b7c",
      "path": "/vue/note/"
    },
    {
      "title": "OSCHINA - 中文开源技术交流社区",
      "frontmatter": {},
      "regularPath": "/vue/excellent/",
      "relativePath": "vue/excellent/README.md",
      "key": "v-2a164f76",
      "path": "/vue/excellent/"
    },
    {
      "frontmatter": {},
      "regularPath": "/vue/source/",
      "relativePath": "vue/source/README.md",
      "key": "v-b2bb5ebc",
      "path": "/vue/source/"
    },
    {
      "frontmatter": {},
      "regularPath": "/link/",
      "relativePath": "link/README.md",
      "key": "v-151077bc",
      "path": "/link/"
    },
    {
      "frontmatter": {},
      "regularPath": "/webframe/vue.html",
      "relativePath": "webframe/vue.md",
      "key": "v-1c074e96",
      "path": "/webframe/vue.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/webframe/",
      "relativePath": "webframe/README.md",
      "key": "v-afc431fc",
      "path": "/webframe/"
    },
    {
      "title": "es6 目录",
      "frontmatter": {},
      "regularPath": "/webframe/es6/",
      "relativePath": "webframe/es6/README.md",
      "key": "v-01aac022",
      "path": "/webframe/es6/",
      "headers": [
        {
          "level": 2,
          "title": "es6 目录",
          "slug": "es6-目录"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/webframe/vue/vue.html",
      "relativePath": "webframe/vue/vue.md",
      "key": "v-e34c2ff2",
      "path": "/webframe/vue/vue.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/works/",
      "relativePath": "works/README.md",
      "key": "v-3e7c18e8",
      "path": "/works/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "前端",
        "link": "/fe/"
      },
      {
        "text": "es6",
        "link": "/es6/"
      },
      {
        "text": "实例",
        "link": "/codes/"
      },
      {
        "text": "前端框架",
        "items": [
          {
            "text": "vue",
            "link": "/vue/"
          }
        ]
      },
      {
        "text": "社区",
        "items": [
          {
            "text": "技术站",
            "items": [
              {
                "text": "掘金",
                "link": "https://juejin.im/user/1310273588955581"
              },
              {
                "text": "github",
                "link": "https://github.com/mhxy13867806343"
              },
              {
                "text": "微博",
                "link": "https://weibo.com/fangjiayu1107"
              }
            ]
          },
          {
            "text": "笔记-语雀",
            "items": [
              {
                "text": "常用导航栏",
                "link": "https://www.yuque.com/jscode/mu1sm1/yorp39"
              },
              {
                "text": "有关在vue2中使用@vue/composition-api与unplugin-vue2-script-setup使用记录说明",
                "link": "https://www.yuque.com/jscode/rd7to5/dmlcys"
              }
            ]
          }
        ]
      },
      {
        "text": "作品",
        "link": "/works/"
      },
      {
        "text": "关于",
        "link": "/about/"
      },
      {
        "text": "未来",
        "link": "/future/"
      }
    ],
    "sidebar": {
      "/fe/": [
        [
          "",
          "前端首页"
        ],
        {
          "title": "资源",
          "path": "/fe/source/",
          "collapsable": false,
          "sidebarDepth": 1
        },
        {
          "title": "html",
          "path": "/fe/html/",
          "collapsable": false,
          "sidebarDepth": 1
        },
        {
          "title": "css",
          "path": "/fe/css/",
          "collapsable": false,
          "sidebarDepth": 1,
          "children": [
            {
              "title": "css世界",
              "path": "css/world/"
            }
          ]
        },
        {
          "title": "js",
          "path": "/fe/js/",
          "collapsable": false,
          "sidebarDepth": 1,
          "children": [
            {
              "title": "你不知道js上中下",
              "path": "js/js/"
            },
            {
              "title": "webpack",
              "path": "js/webpack/"
            },
            {
              "title": "设计模式和数据结构",
              "path": "js/design-patterns-and-data-structures/"
            }
          ]
        },
        {
          "title": "其他",
          "path": "/fe/qt/",
          "collapsable": false,
          "sidebarDepth": 1
        }
      ],
      "/vue/": [
        [
          "",
          "vue首页"
        ],
        {
          "title": "我的笔记",
          "path": "/vue/note/",
          "collapsable": false,
          "sidebarDepth": 1
        },
        {
          "title": "资源",
          "path": "/vue/source/",
          "collapsable": false,
          "sidebarDepth": 1
        }
      ],
      "/link/": [
        [
          "",
          "链接目录"
        ],
        {
          "title": "资源",
          "path": "/link/source/",
          "collapsable": false,
          "sidebarDepth": 1
        }
      ],
      "/es6/": [
        [
          "",
          "es6目录"
        ],
        {
          "title": "笔记",
          "path": "/es6/note/",
          "collapsable": false,
          "sidebarDepth": 1
        },
        {
          "title": "常用",
          "path": "/es6/commonly/",
          "collapsable": false,
          "sidebarDepth": 1
        }
      ]
    }
  }
}